name: Publish Website to GitHub Pages
on:
  push:
    branches:
    - stable

jobs:
  publish_release:
    if: github.repository_owner == 'Synodic-Software'
    uses: synodic-software/.github/.github/workflows/website-publish-pages.yml@stable