name: Draft

on:
  workflow_call:

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        if: ${{ !github.event.repository.fork }}
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
