name: Python Dependencies

on:
  workflow_call:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
