name: Python Publish

on:
  workflow_call:
    inputs:
      repository_url:
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true
jobs:
  pypi_release_deployment:
    if: github.event_name == 'release' && github.event.action == 'published' && ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.10"
          enable-pep582: true

      - name: Build
        run: pdm build -d dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ inputs.repository_url }}
