name: Python Check

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}
          enable-pep582: true

      - name: Install Dependencies
        run: pdm install

      - name: Test
        run: pdm run pytest tests/

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"

      - name: isort
        uses: isort/isort-action@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install 
        run: pip install pylint

      - name: Pylint 
        run: pylint $(git ls-files '*.py')

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install 
        run: pip install mypy

      - name: Mypy 
        run: mypy $(git ls-files '*.py')

